name: Release

on:
  push:
    tags: ["mgns-[0-9]+*"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      # - name: Test
      #   run: cargo test --release
      - name: Build
        run: cargo build --release
      - name: Upload executable as artifact
        uses: actions/upload-artifact@v3
        with:
          name: alacritty
          path: ./target/release/alacritty.exe
      # - name: Upload portable executable
      #   run: |
      #     cp ./target/release/alacritty.exe ./Alacritty-${GITHUB_REF##*/}-portable.exe
      #     ./.github/workflows/upload_asset.sh \
      #       ./Alacritty-${GITHUB_REF##*/}-portable.exe $GITHUB_TOKEN
